### ISSUE TITLE
underscores in branch name/hostname

### ISSUE THREAD

**Issue by paulie4** [layervault/divergence#9]
Underscores are perfectly valid in Git branch names, but `Rack::Lint` throws an assertion error since underscores are not valid in hostnames. Maybe when Divergence starts up, it should check that no branch names have underscores and warn the user. I had to do quite a bit of digging to figure out that the problem was an underscore, since this error isn't very informative:
`Rack::Lint::LintError: env missing required key SERVER_NAME`

**Comment by meltingice** [comment]
Apologizes, I thought this was explained in the README, but it seems it isn't. From the divergence homepage:

Divergence allows you to easily view any branch from your repository by using the branch name as the subdomain. Replace invalid URL characters with dashes and Divergence will magically find the branch you're looking for.

I'll update the README to include this info.
